relearn/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import TemplateView

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns(
    '',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^css/$', 'relearn.views.css', name='css'),
    url(r'^$', 'relearn.views.home', name='home'),
    url(r'^accounts/login$', 'django.contrib.auth.views.login',
        {'template_name': 'login.html'}, name='login'),
    url(r'^accounts/logout$', 'django.contrib.auth.views.logout',
        {'template_name': 'logout.html'}, name='logout'),
    url(r'^accounts/profile$', 'relearn.views.profile', name='profile'),
    url(r'^etherpad/create/(?P<pk>\d+)/$', 'relearn.views.padCreate', name='pad-create'),
    url(r'^etherpad/delete/(?P<pk>\d+)/$', 'relearn.views.padDelete', name='pad-delete'),
    url(r'^group/create$', 'relearn.views.groupCreate'),
    url(r'r/(?P<slug>[\w\.\-_\:]+)$', 'relearn.views.pad_read', name='pad-read'),
    url(r'w/(?P<slug>[\w\.\-_\:]+)$', 'relearn.views.pad', name='pad-write'),
)

relearn/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _


class ContactForm(forms.Form):
    name         = forms.CharField(max_length=50, label=_("First Name"))
    email        = forms.EmailField(label=_("E-Mail"))
    subject      = forms.CharField(max_length=100, label=_("Subject"))
    message      = forms.CharField(widget=forms.Textarea(), label=_("Message"))

relearn/views.py
# -*- coding: utf-8 -*-

# Python imports
import datetime
import time
import urllib
from urlparse import urlparse
import HTMLParser
import json
import re
import os

# PyPi imports

from markdown import markdown
from py_etherpad import EtherpadLiteClient

# Framework imports
from django.shortcuts import render_to_response, get_object_or_404

from django.http import HttpResponse, HttpResponseRedirect
from django.template import RequestContext
from django.template.defaultfilters import slugify
from django.core.urlresolvers import reverse
from django.core.context_processors import csrf
from django.contrib.auth.decorators import login_required
from django.utils.translation import ugettext_lazy as _

# Django Apps import

from etherpadlite.models import *
from etherpadlite import forms
from etherpadlite import config

from django.shortcuts import render
from django.core.mail import send_mail
from relearn.forms import ContactForm

from relearn.templatetags.wikify import dewikify

"""
Set up an HTMLParser for the sole purpose of unescaping
Etherpad’s HTML entities.
cf http://fredericiana.com/2010/10/08/decoding-html-entities-to-text-in-python/
"""

h = HTMLParser.HTMLParser()
unescape = h.unescape

@login_required(login_url='/accounts/login')
def padCreate(request, pk):
    """Create a named pad for the given group
    So this is kind of convoluted. With an input like
    
    Relearn::Can it scale to the universe
    
    we get a pad, with the unchangeable id:
    relearn::can-it-scale-to-the-universe
    and the name / display_slug:
    Relearn::Can_it_scale_to_the_universe
    
    The title of pages is displayed through a slight transformation,
    known as dewikify.
    _ becomes space, :: → as in:
    Relearn → can it scale to the universe
    """
    group = get_object_or_404(PadGroup, pk=pk)

    if request.method == 'POST':  # Process the form
        form = forms.PadCreate(request.POST)
        if form.is_valid():
            n = form.cleaned_data['name']
            basename = slugify(n)[:42]
            n = re.sub(r'\s+', u'_', n)
            pad = Pad(
                name=basename,
                display_slug=n,
                display_name=n,     # this is just for backwards compatibility
                server=group.server,
                group=group
            )
            pad.save()
            return HttpResponseRedirect(reverse('pad-write', args=(n,) ))
    else:  # No form to process so create a fresh one
        form = forms.PadCreate({'group': group.groupID})

    con = {
        'form': form,
        'pk': pk,
        'title': _('Create pad in %(grp)s') % {'grp': group.__unicode__()}
    }
    con.update(csrf(request))
    return render_to_response(
        'pad-create.html',
        con,
        context_instance=RequestContext(request)
    )


@login_required(login_url='/accounts/login')
def padDelete(request, pk):
    """Delete a given pad
    """
    pad = get_object_or_404(Pad, pk=pk)

    # Any form submissions will send us back to the profile
    if request.method == 'POST':
        if 'confirm' in request.POST:
            pad.delete()
        return HttpResponseRedirect(reverse('profile'))

    con = {
        'action': '/etherpad/delete/' + pk + '/',
        'question': _('Really delete this pad?'),
        'title': _('Deleting %(pad)s') % {'pad': pad.__unicode__()}
    }
    con.update(csrf(request))
    return render_to_response(
        'etherpad-lite/confirm.html',
        con,
        context_instance=RequestContext(request)
    )


@login_required(login_url='/accounts/login')
def groupCreate(request):
    """ Create a new Group
    """
    message = ""
    if request.method == 'POST':  # Process the form
        form = forms.GroupCreate(request.POST)
        if form.is_valid():
            group = form.save()
            # temporarily it is not nessessary to specify a server, so we take
            # the first one we get.
            server = PadServer.objects.all()[0]
            pad_group = PadGroup(group=group, server=server)
            pad_group.save()
            request.user.groups.add(group)
            return HttpResponseRedirect(reverse('profile'))
        else:
            message = _("This Groupname is allready in use or invalid.")
    else:  # No form to process so create a fresh one
        form = forms.GroupCreate()
    con = {
        'form': form,
        'title': _('Create a new Group'),
        'message': message,
    }
    con.update(csrf(request))
    return render_to_response(
        'etherpad-lite/groupCreate.html',
        con,
        context_instance=RequestContext(request)
    )


@login_required(login_url='/accounts/login')
def groupDelete(request, pk):
    """
    """
    pass


@login_required(login_url='/accounts/login')
def profile(request):
    """Display a user profile containing etherpad groups and associated pads
    """
    name = request.user.__unicode__()

    try:  # Retrieve the corresponding padauthor object
        author = PadAuthor.objects.get(user=request.user)
    except PadAuthor.DoesNotExist:  # None exists, so create one
        author = PadAuthor(
            user=request.user,
            server=PadServer.objects.get(id=1)
        )
        author.save()
    author.GroupSynch()

    groups = {}
    for g in author.group.all():
        groups[g.__unicode__()] = {
            'group': g,
            'pads': Pad.objects.filter(group=g)
        }

    return render_to_response(
        'etherpad-lite/profile.html',
        {
            'name': name,
            'author': author,
            'groups': groups
        },
        context_instance=RequestContext(request)
    )


@login_required(login_url='/accounts/login')
def pad(request, pk=None, slug=None):
    """Create and session and display an embedded pad
    """

    # Initialize some needed values
    if slug:
        pad = get_object_or_404(Pad, display_slug=slug)
    else:
        pad = get_object_or_404(Pad, pk=pk)
    padLink = pad.server.url + 'p/' + pad.group.groupID + '$' + \
        urllib.quote_plus(pad.name)
    server = urlparse(pad.server.url)
    author = PadAuthor.objects.get(user=request.user)

    if author not in pad.group.authors.all():
        response = render_to_response(
            'pad.html',
            {
                'pad': pad,
                'link': padLink,
                'server': server,
                'uname': author.user.__unicode__(),
                'error': _('You are not allowed to view or edit this pad')
            },
            context_instance=RequestContext(request)
        )
        return response

    # Create the session on the etherpad-lite side
    expires = datetime.datetime.utcnow() + datetime.timedelta(
        seconds=config.SESSION_LENGTH
    )
    epclient = EtherpadLiteClient(pad.server.apikey, pad.server.apiurl)

    try:
        result = epclient.createSession(
            pad.group.groupID,
            author.authorID,
            time.mktime(expires.timetuple()).__str__()
        )
    except Exception, e:
        response = render_to_response(
            'pad.html',
            {
                'pad': pad,
                'link': padLink,
                'server': server,
                'uname': author.user.__unicode__(),
                'error': _('etherpad-lite session request returned:') +
                ' "' + e.reason + '"'
            },
            context_instance=RequestContext(request)
        )
        return response

    # Set up the response
    response = render_to_response(
        'pad.html',
        {
            'pad': pad,
            'link': padLink,
            'server': server,
            'uname': author.user.__unicode__(),
            'error': False,
            'mode' : 'write'
        },
        context_instance=RequestContext(request)
    )

    # Delete the existing session first
    if ('padSessionID' in request.COOKIES):
        if 'sessionID' in request.COOKIES.keys():
            try:
                epclient.deleteSession(request.COOKIES['sessionID'])
            except ValueError:
                response.delete_cookie('sessionID', server.hostname)
        response.delete_cookie('padSessionID')

    # Set the new session cookie for both the server and the local site
    response.set_cookie(
        'sessionID',
        value=result['sessionID'],
        expires=expires,
        domain=server.hostname,
        httponly=False
    )
    response.set_cookie(
        'padSessionID',
        value=result['sessionID'],
        expires=expires,
        httponly=False
    )
    return response

def pad_read(request, pk=None, slug=None):
    """Read only pad
    """

    # Initialize some needed values
    if slug:
        pad = get_object_or_404(Pad, display_slug=slug)
    else:
        pad = get_object_or_404(Pad, pk=pk)
    
    padID = pad.group.groupID + '$' + urllib.quote_plus(pad.name.replace('::', '_'))
    epclient = EtherpadLiteClient(pad.server.apikey, pad.server.apiurl)
    
    # Etherpad gives us authorIDs in the form ['a.5hBzfuNdqX6gQhgz', 'a.tLCCEnNVJ5aXkyVI']
    # We link them to the Django users DjangoEtherpadLite created for us
    authorIDs = epclient.listAuthorsOfPad(padID)['authorIDs']
    authors = PadAuthor.objects.filter(authorID__in=authorIDs)
    
    authorship_authors = []
    for author in authors:
        authorship_authors.append({ 'name'  : author.user.first_name if author.user.first_name else author.user.username,
                                    'class' : 'author' + author.authorID.replace('.','_') })
    authorship_authors_json = json.dumps(authorship_authors, indent=2)
    
    name, extension = os.path.splitext(slug)
    if not extension:
        # Etherpad has a quasi-WYSIWYG functionality.
        # Though is not alwasy dependable
        text = epclient.getHtml(padID)['html']
        # Quick and dirty hack to allow HTML in pads
        text = unescape(text)
    else:

relearn/templates/base.html
{% load wikify %}
<!DOCTYPE HTML>
<html>
<head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8">
    <link rel="stylesheet" href="{{ STATIC_URL }}css/reset.css" type="text/css" charset="utf-8">
    <link rel="stylesheet" href="{{ STATIC_URL }}css/fonts.css" type="text/css" charset="utf-8">
    <link rel="stylesheet" href="/css/" type="text/css" charset="utf-8">
    <link rel="stylesheet" href="{{ STATIC_URL }}css/print.css" media="print" type="text/css" charset="utf-8"> 
    <script src="{{ STATIC_URL }}js/less-1.4.1.min.js" type="text/javascript" charset="utf-8"></script>
    <script src="{{ STATIC_URL }}js/jquery-1.10.2.min.js" type="text/javascript" charset="utf-8"></script>
    <script src="{{ STATIC_URL }}js/underscore-min.js" type="text/javascript" charset="utf-8"></script>

    <title>{{ site_name }}{% if pad %} → {{ pad.display_slug|dewikify }}{% endif %}</title>

    {% block extra_styles %}{% endblock %}
    
</head>
<body>
    <div class="wrap screen-only" style="min-height: 15%;">
        <div class="left-side">
            <h1><a href="{% url 'home' %}">{{ site_name }}</a></h1>
        </div>
        <div class="middle">
            {% block title %}{% endblock %}
        </div>

        <div class="right-side">
            <ul id="account-buttons">
                {% if user.is_authenticated and author %}<li>{{ author.full_name_with_prefix }}</li>
                <li><a class="button" href="{% url 'logout' %}">Log out</a></li>{% else %}
                <li><a class="button" href="{% url 'login' %}">Log in</a></li>{% endif %}
            </ul>
        </div>
    </div>


    <div class="wrap" style="height: 85%;">
        <div class="left-side screen-only">
            <nav>
                <ul>
                    {% if author %}
                        <li id="create-pad"><a class="button" href="{% url 'pad-create' author.group.all.0.id %}">Create pad</a></li>
                    {% endif %}
                </ul>
                <ul id="pads_list">
                    {% for pad in pads %}
                        <li><a data-uid="{{ pad.display_slug }}" href="{% if mode == 'write' %}{% url 'pad-write' slug=pad.display_slug %}{% else %}{% url 'pad-read' slug=pad.display_slug %}{% endif %}" class="pad-link">{{ pad.display_slug|dewikify }}</a></li>
                    {% endfor %}
                </ul>
            </nav>
        </div>
        <div id="content" class="middle {% block contentclasses %}{% endblock %}">
            {% block content %}{% endblock %}
        </div>
        <div class="right-side screen-only">
            <h2>The right side</h2>
        </div>
    </div>
    <script src="{{ STATIC_URL }}js/relearn.js" type="text/javascript" charset="utf-8"></script>
{% block scripts %}{% endblock %}
</body>
</html>

relearn/templates/commits.html
<div class="commits">
{% extends "base.html" %}

{% block contentclasses %}commits-col{% endblock %}

{% block content %}
            {% for commit in all_commits %}
            <h3>{{ commit.repo_name }}</h3>
            <p class='commit-message'>{{ commit.message|urlize|linebreaksbr }}</p>
            <p>By <span class='commit-author'>{{ commit.author }}</span> on <span class='commit-date'>{{ commit.commit_time }}</span></p>

            {% endfor %}
{% endblock %}
</div>

relearn/templates/form.html
<!DOCTYPE HTML>
<html>
<head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8">
    <title>Relearn</title>
    <link rel="stylesheet/less" href="{{ STATIC_URL }}less/relearn.less" type="text/css" media="screen" charset="utf-8">
    <script src="{{ STATIC_URL }}js/less-1.4.1.min.js" type="text/javascript" charset="utf-8"></script>
    <style type="text/css" media="screen">
        body {
            background: none;
        }
        
    </style>
</head>
<body>
<form id="email-form" action="{% url 'relearn-issue-send' %}" method="post" accept-charset="utf-8">
    {% csrf_token %}
    <div>
        <input style="width: 45%; display: inline; margin-right: 10px;" id="id_name" maxlength="50" name="name" type="text" value="{{ user.get_full_name }}"/>
        <!--<input style="width: 45%; display: inline;" id="id_email" name="email" type="text" value="{{ user.email }}" />-->
    </div>
    <div style="margin-top: 3px;">
        <label style="width: 25%; display: inline;" for="id_subject">Subject</label> 
        <input style="width: 73%; display: inline;" id="id_subject" maxlength="100" name="subject" type="text" />
    </div>
    <div style="margin-top: 3px;">
        <textarea style="width: 96%; height: 6em;" id="id_message" name="message"></textarea>
    </div>
    <p><input type="submit" value="Send"></p>
</form>
</body>
</html>

relearn/templates/issue.html
<!DOCTYPE HTML>
<html>
<head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8">
    <title>Relearn</title>
    <link rel="stylesheet/less" href="{{ STATIC_URL }}less/relearn.less" type="text/css" media="screen" charset="utf-8">
    <script src="{{ STATIC_URL }}js/less-1.4.1.min.js" type="text/javascript" charset="utf-8"></script>
    <style type="text/css" media="screen">
        body {
            background: none;
        }
        
    </style>
</head>
<body>
    <p>Your issue has been sent. You will receive it through the mailing-list and out of the printer in the common room.</<p>
    <p><a href="/send-issue/">Point out another issue.</a></p>
    
</body>
</html>

relearn/templates/login.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}
    <h1>{% trans "Login" %}</h1>
{% endblock %}

{% block content %}
  {% if not user.is_authenticated %}
      {% if form.errors %}
      <p class="error">{% trans "Your username and password didn't match. Please try again." %}</p>
      {% endif %}
    
      <form method="post" action="{% url 'django.contrib.auth.views.login' %}">
        {% csrf_token %}
            {{ form.username.label_tag }}
            {{ form.username }}
            {{ form.password.label_tag }}
            {{ form.password }}
    
        <input class="submit" type="submit" value="{% trans "Login" %}" />
        <input type="hidden" name="next" value="{% if next %}{{ next }}{% else %}{% url 'home' %}{% endif %}" />
      </form>
    {% else %}
    <p>You are already logged in—welcome!</p>
    {% endif %}
{% endblock %}

relearn/templates/logout.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}
<h1>{% trans "Logout" %}</h1>
{% endblock %}

{% block content %}
<h2>{% trans "You have been logged out." %} <a href="{% url 'login' %}">{% trans "Log back in." %}</a></h2>

{% endblock %}

relearn/templates/pad-base.html
{% extends "base.html" %}

{% block title %}

<h1 class="inline">{{ pad.display_slug }}</h1>

<div id="switch">
    {% if mode == 'read' %}
        <a class="active button">Read</a><a class="button" href="{% url 'pad-write' pad.display_slug %}">Write</a>
    {% else %}
        <a class="button" href="{% url 'pad-read' pad.display_slug %}">Read</a><a class="active button">Write</a>
    {% endif %}
	<a class="button" href="#" onclick="window.print()">Print</a>
</div>

{% endblock %}

{% block extra_styles %}{% if "notes" in namespaces %} 
	<link rel="stylesheet" href="{{ STATIC_URL }}less/print_notes.css" type="text/css" charset="utf-8">
{% endif %}{% endblock %}

{% block contentclasses %}{% for namespace in namespaces %}{{ namespace }} {% endfor %}{% endblock %}

relearn/templates/pad-create.html
{% extends "base.html" %}
{% load url from future %}
{% load i18n %}

{% block title %}
      <h1>{{ title }}</h1>
{% endblock %}

{% block content %}
  <form action="/etherpad/create/{{ pk }}/" method="post">
        {% csrf_token %}
        Pad name
        {{ form.name }}
        {{ form.group }}
        <input class="submit" type="submit" value="{%trans "Create" %}" />
  </form>
  <legend>Names will be normalised to url-like names: <br />
        «Can it scale to the universe?» becomes «can-it-scale-to-the-universe».<br />
    Use “::” to create sub-divisions, i.e. «pedagogy::references».
    </legend>
{% endblock %}

relearn/templates/pad-read.html
{% extends "pad-base.html" %}
{% load wikify %}

{% block content %}
<h1 class="print-only">{{ pad.display_slug|dewikify }}</h1>
{% if authors %}
<ul class="authors">
{% for author in authors %}
    <li>{{ author }}</li>
{% endfor %}
</ul>
{% endif %}
{{ text|safe }}
{% endblock %}

{% block scripts %}
<script>
    /* Convert links to images in images */
   
    var isImg = new RegExp('\.png|\.jpg|\.jpeg|\.gif', 'i');
    
    $("a[href]").each(function() {
        if ( $(this).attr('href').match(isImg) ) {
            $(this).html('<img src="' + $(this).attr('href')  + '">');
        }
    });

{% if "notes" in namespaces %}

    // for the notes we want detailed authorship information,
    // to tell us something about the process.
    // django provides us with the authors:
    
    var authors = {{ authorship_authors_json|safe }}
    
    for (var i=0; i < authors.length; i++) {
    // for all the author, we’re going to go over all the spans,
    // and add authorship labels if they correspond
    
    // if we have consecutive spans with the same author,
    // it only adds a lable for the first one.
    
        var author = authors[i]; 
        
        var currentAuthor = '';
        $('span').each(function() {
            var thisClass = $(this).attr('class');
            
            // for the first span it encounters, currentAuthor is empty,
            // so that always gets a label
            
            if ( thisClass !== currentAuthor) {

                // if the class has a classname that corresponds to the author
                // then we insert the label
                
                if (thisClass === author.class ) {
                    $(this).before('<span class="authorship">' + author.name + '</span>')
                }
                
                // set currentAuthor, so that if the next span shares this author it
                // doesn’t get labeled
                
                currentAuthor = thisClass;
                
            }
        });
    }
{% endif %}
</script>
{% endblock %}

relearn/templates/pad.html
{% extends "pad-base.html" %}

{% block content %}
  {% if error %}
  <div id="main">
    <div id="errors">
      <h2>Errors:</h2>
      <p>{{error}}</p>
    </div>
  </div>
  {% else %}
  <iframe id="ether" src="{{link}}?userName={{uname}}" style="height: 95%; width: 100%; min-height: 500px; display: block"></iframe>

  <script type="text/javascript">
  /**
   * This little script is necessary for some browsers that don't respect the
   * height css attribute on iframes.
   */
  function resizeEtherpad() {
    height = jQuery(window).height()*94/100;
    jQuery('#wrapper iframe').height(height);
  }

  jQuery(document).ready( function() {
    resizeEtherpad()
    jQuery(window).resize(resizeEtherpad);
  });
  </script>
  {% endif %}

{% endblock %}

relearn/templates/tracker.html
{% extends "base.html" %}

{% block content %}
<h1>Tracker</h1>
<form action="tracker_submit" method="get" accept-charset="utf-8">
    <p><label>ID</label><input name="id" type="text" value="" /></p>
    <p><label>Date/Time</label><input name="datetime" type="text" value="" /></p>
    <p><label>Name</label><input name="name" type="text" value="" /></p>
    <p><label>Text</label><textarea name="text" cols="80" rows="10" value=""></textarea></p>
    <p><input type="submit" value="Continue &rarr;" /></p>
</form>
{% endblock %}